### PR TITLE
aimbot lua script, added more sdk/binds

### PR DESCRIPTION
**Pull request by starcon2**

### CODE REVIEW

**Comment by starcon2** [comment]
ok, pretty sure i fixed the issues.

**Comment by xrivendell** [comment]
There are still lua and luabind binares, remove them and restore README.md file.

**Comment by xrivendell** [comment]
I forgot about the main.lua script, if you want to add an example add it to the examples folder.

**Comment by starcon2** [comment]
Ok, I'm pretty sure i've did everything you've told me too.

**Pull request merged**
